services:
  euroturbot:
    build:
      context: ./automatizacion
      dockerfile: Dockerfile

    container_name: euroturbot-monitor

    ports:
      - "8500:8000"

    env_file:
      - ./automatizacion/.env

    volumes:
      - ./automatizacion/input:/app/automatizacion/input
      - ./automatizacion/processed:/app/automatizacion/processed
      - ./automatizacion/outputs:/app/automatizacion/outputs

    shm_size: "256mb"

    restart: unless-stopped
